spring:
  datasource:
    url: jdbc:mysql://localhost:3306/netmed_dev
    username: ${dbusername}
    password: ${dbpassword}
    driver-class-name: com.mysql.jdbc.Driver
	data:
		mongodb:
			uri: ${mongocred}
