spring:
  application:
    name: netmed-user-module
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true  
  datasource:
    url: jdbc:mysql://localhost:3306/netmed_dev
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace